@startuml
abstract class PropertySpace {
    + enterSpace(player: Player, steps: int): String
    + getRent(steps: int): int {abstract}
}
class ColoredPropertySpace extends PropertySpace {
    + getRent(steps: int): int
}
class RailroadSpace extends PropertySpace {
    + getRent(steps: int): int
}
class UtilitySpace extends PropertySpace {
    + getRent(steps: int): int
}
@enduml